//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareInfo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HardwareInfo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        public static string Accelerometer {
            get {
                return ResourceManager.GetString("Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Info.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery sensor.
        /// </summary>
        public static string BatterySensor {
            get {
                return ResourceManager.GetString("BatterySensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve hardware information.
        /// </summary>
        public static string CheckHWText {
            get {
                return ResourceManager.GetString("CheckHWText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM Radio.
        /// </summary>
        public static string FMRadio {
            get {
                return ResourceManager.GetString("FMRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front camera.
        /// </summary>
        public static string FrontCamera {
            get {
                return ResourceManager.GetString("FrontCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front camera flash.
        /// </summary>
        public static string FrontCameraFlash {
            get {
                return ResourceManager.GetString("FrontCameraFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyroscope.
        /// </summary>
        public static string Gyroscope {
            get {
                return ResourceManager.GetString("Gyroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinometer.
        /// </summary>
        public static string Inclinometer {
            get {
                return ResourceManager.GetString("Inclinometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion API.
        /// </summary>
        public static string MotionApi {
            get {
                return ResourceManager.GetString("MotionApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC.
        /// </summary>
        public static string NFC {
            get {
                return ResourceManager.GetString("NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation sensor.
        /// </summary>
        public static string OrientationSensor {
            get {
                return ResourceManager.GetString("OrientationSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary camera.
        /// </summary>
        public static string PrimaryCamera {
            get {
                return ResourceManager.GetString("PrimaryCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary camera flash.
        /// </summary>
        public static string PrimaryCameraFlash {
            get {
                return ResourceManager.GetString("PrimaryCameraFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD card present.
        /// </summary>
        public static string SDCard {
            get {
                return ResourceManager.GetString("SDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string VersionNumberString {
            get {
                return ResourceManager.GetString("VersionNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration device.
        /// </summary>
        public static string VibrationDevice {
            get {
                return ResourceManager.GetString("VibrationDevice", resourceCulture);
            }
        }
    }
}
