//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneInfo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneInfo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutLower {
            get {
                return ResourceManager.GetString("AboutLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About phone.
        /// </summary>
        public static string AboutPhone {
            get {
                return ResourceManager.GetString("AboutPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        public static string Accelerometer {
            get {
                return ResourceManager.GetString("Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Info.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE INFO.
        /// </summary>
        public static string ApplicationTitleUpper {
            get {
                return ResourceManager.GetString("ApplicationTitleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App memory.
        /// </summary>
        public static string AppMemory {
            get {
                return ResourceManager.GetString("AppMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App memory peaked at.
        /// </summary>
        public static string AppMemoryPeakedAt {
            get {
                return ResourceManager.GetString("AppMemoryPeakedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery &amp; power.
        /// </summary>
        public static string BatteryAndPower {
            get {
                return ResourceManager.GetString("BatteryAndPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery status information.
        /// </summary>
        public static string BatteryStatusInfo {
            get {
                return ResourceManager.GetString("BatteryStatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string CameraItemsTitle {
            get {
                return ResourceManager.GetString("CameraItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        public static string ConnectedToExternalPowerSupply {
            get {
                return ResourceManager.GetString("ConnectedToExternalPowerSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currently in use of.
        /// </summary>
        public static string CurrentlyInUseOf {
            get {
                return ResourceManager.GetString("CurrentlyInUseOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device total memory.
        /// </summary>
        public static string DeviceTotalMemory {
            get {
                return ResourceManager.GetString("DeviceTotalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display size.
        /// </summary>
        public static string DisplaySize {
            get {
                return ResourceManager.GetString("DisplaySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        public static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM Radio.
        /// </summary>
        public static string FMRadio {
            get {
                return ResourceManager.GetString("FMRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front camera.
        /// </summary>
        public static string FrontCamera {
            get {
                return ResourceManager.GetString("FrontCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front camera flash.
        /// </summary>
        public static string FrontCameraFlash {
            get {
                return ResourceManager.GetString("FrontCameraFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTitle {
            get {
                return ResourceManager.GetString("GeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyroscope.
        /// </summary>
        public static string Gyroscope {
            get {
                return ResourceManager.GetString("Gyroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware version.
        /// </summary>
        public static string HardwareVersion {
            get {
                return ResourceManager.GetString("HardwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        public static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinometer.
        /// </summary>
        public static string Inclinometer {
            get {
                return ResourceManager.GetString("Inclinometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion API.
        /// </summary>
        public static string MotionApi {
            get {
                return ResourceManager.GetString("MotionApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC.
        /// </summary>
        public static string NFC {
            get {
                return ResourceManager.GetString("NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation sensor.
        /// </summary>
        public static string OrientationSensor {
            get {
                return ResourceManager.GetString("OrientationSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string OthersTitle {
            get {
                return ResourceManager.GetString("OthersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        public static string Pixels {
            get {
                return ResourceManager.GetString("Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back camera.
        /// </summary>
        public static string PrimaryCamera {
            get {
                return ResourceManager.GetString("PrimaryCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back camera flash.
        /// </summary>
        public static string PrimaryCameraFlash {
            get {
                return ResourceManager.GetString("PrimaryCameraFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen/display.
        /// </summary>
        public static string ScreenDisplay {
            get {
                return ResourceManager.GetString("ScreenDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen resolution.
        /// </summary>
        public static string ScreenResolution {
            get {
                return ResourceManager.GetString("ScreenResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD card present.
        /// </summary>
        public static string SDCard {
            get {
                return ResourceManager.GetString("SDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorItemsTitle {
            get {
                return ResourceManager.GetString("SensorItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme accent color.
        /// </summary>
        public static string ThemeAccentColor {
            get {
                return ResourceManager.GetString("ThemeAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration device.
        /// </summary>
        public static string VibrationDevice {
            get {
                return ResourceManager.GetString("VibrationDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
